name: 'React CD pipline'

on:
    workflow_run:
      workflows: ['React CI pipeline']
      types:
        - completed

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:

            - name: 'Setup node'
              uses: actions/setup-node@v4
              with:
                node-version: '20'

            - name: 'Download atifacts'
              uses: actions/download-artifact@v4
              with:
                name: build
                run-id: ${{ github.event.workflow_run.id }}
                github-token: ${{ github.token }}