name: 'React CI pipeline'

on:
    push:
        branches:
          - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: 'Setting up node js'
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            
            - name: 'Clone repo' # This are new runner server provided by github so they dont have node and also they dont have your repo so we need to clone it here
              uses: actions/checkout@v4

            - name: 'Install dependencies'
              run: npm install

            - name: 'List dirs'
              run: ls
            
            - name: 'Running Test case' # To run test case if any malitious code pushed
              run: npm run test
            - name: 'Create project build' # If test case fails then build step will not be executed
              run: npm run build
            
            - name: 'List dirs'
              run: ls

            # Now if we and o transfer/share data between pipline we can take help of artifacts
            # Artifcat is place where we will upload our build folder and later download for CD pipline
            - name: 'Upload product-ready build' 
              uses: actions/upload-artifact@v4
              with:
                name: build # we need to provide name and path of action
                path: dist #path of build folder